name: Build Qrack installers

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch (adjust if needed)
      - development

  workflow_dispatch: # Allow manual triggering of the workflow


jobs:
  build_linux:
    runs-on: ubuntu-latest  # Use a Linux runner
    strategy:
      matrix:
        platform:
          - manylinux_2_39_x86_64
          - manylinux_2_35_x86_64
          - linux_aarch64
          - linux_armv7l
          - manylinux2014_x86_64
          - macosx_10_4_universal2
    steps:
      - name: Checkout Qrack
        uses: actions/checkout@v4

      - name: Prepare Build Environment (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ocl-icd-opencl-dev opencl-headers

      - name: Install Homebrew (MacOS)
        if: runner.os == 'macOS'
        uses: Homebrew/actions/setup-homebrew@master

      - name: Prepare Build Environment (MacOS)
        if: runner.os == 'macOS'
        run: |
          brew install cmake opencl-clhpp-headers

      - name: Build Qrack Linux x86-64
        if: matrix.platform == 'manylinux_2_39_x86_64' || matrix.platform == 'manylinux_2_35_x86_64' || matrix.platform == 'manylinux2014_x86_64'
        run: |
          mkdir build
          cd build
          cmake -DENABLE_RDRAND=OFF -DENABLE_DEVRAND=ON -DQBCAPPOW=12 -DCPP_STD=14 ..
          make all
          sudo cpack

      - name: Build Qrack Linux ARM64
        if: matrix.platform == 'linux_aarch64' || matrix.platform == 'linux_armv7l'
        run: |
          mkdir build
          cd build
          cmake -DENABLE_RDRAND=OFF -DENABLE_DEVRAND=ON -DENABLE_COMPLEX_X2=OFF -DQBCAPPOW=12  -DCPP_STD=14 ..
          make all
          sudo cpack

      - name: Build Qrack MacOS
        if: matrix.platform == 'macosx_10_4_universal2'
        run: |
          mkdir build
          cd build
          cmake -DQBCAPPOW=12 -DCPP_STD=14 ..
          make all
          sudo cpack

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libqrack-${{ matrix.platform }}
          path: |
            build/libqrack-*.sh
            build/benchmarks

  build_windows:
    runs-on: windows-latest  # Use a Linux runner
    strategy:
      matrix:
        platform:
          - win-amd64
          - win-arm32
          - win-arm64
        dependencies: [vcpkg]
    steps:
      - name: Mount vcpkg cache
        uses: actions/cache@v4
        with:
          path: "~/.cache/vcpkg/archives"
          key: vcpkg-${{ matrix.os }}

      - name: Install and integrate vcpkg dependencies
        run: |
          vcpkg install opencl

      - name: Checkout Qrack
        uses: actions/checkout@v4

      - name: Build Qrack Windows x86-64
        if: matrix.platform == 'win-amd64'
        run: |
          mkdir build
          cd build
          powershell -c "Invoke-WebRequest -Uri 'https://github.com/ckormanyos/xxd/releases/download/v1.1/xxd-win64-msvc.zip' -OutFile 'xxd-win64-msvc.zip'"
          powershell -c "Expand-Archive -Path xxd-win64-msvc.zip -DestinationPath ."
          cmake .. -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" -DXXD_BIN="xxd.exe" -DQBCAPPOW=12 -DCPP_STD=14
          echo "cmake --build . --config Release --target PACKAGE benchmarks > nul & exit /b 0" > build.bat
          echo "exit 0" >> build.bat
          cmd /c build.bat

      - name: Build Qrack Windows ARM
        if: matrix.platform == 'win-arm32' || matrix.platform == 'win-arm64'
        run: |
          mkdir build
          cd build
          powershell -c "Invoke-WebRequest -Uri 'https://github.com/ckormanyos/xxd/releases/download/v1.1/xxd-win64-msvc.zip' -OutFile 'xxd-win64-msvc.zip'"
          powershell -c "Expand-Archive -Path xxd-win64-msvc.zip -DestinationPath ."
          cmake .. -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" -DXXD_BIN="xxd.exe" -DENABLE_COMPLEX_X2=OFF -DQBCAPPOW=12 -DCPP_STD=14
          echo "cmake --build . --config Release --target PACKAGE benchmarks > nul & exit /b 0" > build.bat
          echo "exit 0" >> build.bat
          cmd /c build.bat

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libqrack-${{ matrix.platform }}
          path: |
            build/libqrack-*.exe
            build/Release/benchmarks.exe
